version: '3'
services:
  app:
    build: .
    ports:
      - "3000:4000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_management
    ports:
      - "3308:3306"